### ISSUE TITLE
scrim

### ISSUE THREAD

**Issue by abernier** [JavierM42/tailwind-material-colors#10]
Hey, and 1st: thank you so much for this plugin, it is really awesome

Sometime on m3 specs, a `scrim` color role is specified, but we haven't got it in your impl.

Like 9:
<img width="1879" alt="image" src="https://github.com/user-attachments/assets/c3f82a5b-b450-4770-ade8-c8a5e779a62d">

ref https://m3.material.io/styles/elevation/applying-elevation

**Comment by abernier** [comment]
commpared to the color scheme
![image](https://github.com/user-attachments/assets/9cb93af6-fedd-4613-9a6b-35cc3d87e964)
 on https://m3.material.io/styles/color/roles the one this impl provides is slightly different, is that intended?

**Comment by JavierM42** [comment]
Oops. My bad. Thanks for the feedback!

I've added the scrim color (v3.1.0) ✨ 

if it doesn't work as expected, please open another issue.

**Comment by abernier** [comment]
and shadow? 😅

<img width="858" alt="image" src="https://github.com/user-attachments/assets/b8348960-b53c-46cd-9812-ea7665655f7c">

**Comment by abernier** [comment]
oh, and I dunno if this is new, but it is missing ["fixed" accent colors](https://m3.material.io/styles/color/roles#26b6a882-064d-4668-b096-c51142477850)

<img width="858" alt="image" src="https://github.com/user-attachments/assets/c98521d8-5e83-4929-a4af-59cbc37552da">

**Comment by JavierM42** [comment]
Added shadow on `v3.2.2`

**Comment by JavierM42** [comment]
I'll add the `fixed` variants to my TODO list, thanks for the heads up.
