### ISSUE TITLE
Is `harmonize: false` works?

### ISSUE THREAD

**Issue by beautyfree** [JavierM42/tailwind-material-colors#4]

**Comment by JavierM42** [comment]
Could you provide an example where it doesn't work?

Here's a [working example on CodeSandbox](https://codesandbox.io/p/sandbox/tailwind-material-colors-harmonize-example-x5vkp9?file=%2Ftailwind.config.js%3A10%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clops8df700063d6i5xbmg7cs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clops8df600033d6iiwqaywl9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clops8df700043d6izeo7x256%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clops8df700053d6igps656hs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clops8df600033d6iiwqaywl9%2522%253A%257B%2522id%2522%253A%2522clops8df600033d6iiwqaywl9%2522%252C%2522activeTabId%2522%253A%2522clopsb8w900ff3d6i5w8nhup5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clops8df600023d6i0o49te5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftailwind.config.js%2522%252C%2522id%2522%253A%2522clops9n9o008l3d6ifxz8k7yg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522id%2522%253A%2522clopsb8w900ff3d6i5w8nhup5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522id%2522%253A%2522clopszn58004u3d6hvfckef8v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clops8df700053d6igps656hs%2522%253A%257B%2522id%2522%253A%2522clops8df700053d6igps656hs%2522%252C%2522activeTabId%2522%253A%2522clops9ab000683d6i2gotenql%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clops9ab000683d6i2gotenql%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clops8df700043d6izeo7x256%2522%253A%257B%2522id%2522%253A%2522clops8df700043d6izeo7x256%2522%252C%2522activeTabId%2522%253A%2522clops94l9004x3d6ih9t57pzd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clops94l9004x3d6ih9t57pzd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by beautyfree** [comment]
Maybe I don't undestand meaning of turning off of harmonization. 

I though that it keep color in original value (`#e6eeff` in this sandbox)
https://codesandbox.io/p/sandbox/tailwind-material-colors-harmonize-example-forked-5nq956

**Comment by JavierM42** [comment]
I should've been more specific in the README, that's my bad. `harmonize` comes from Material's algorithm and works like this:

- `harmonize: true` will blend your color to the `primary` color.
- `harmonize: false` will not, yields the same color regardless of what your `primary` color is. This does not mean that it will keep the original color value.

How exaclty does Google's algorithm transform your color or blend it with the primary? Not sure, that's on their library.

**Comment by beautyfree** [comment]
Got it, thank you!
